CI syntax fix

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -39,7 +39,7 @@ jobs:
         run: ansible-playbook -i tests/inventory tests/test.yml
 
       - name: Second run to check for indempotence (allow 1 change for status check)
-        run: "ansible-playbook -i tests/inventory tests/test.yml" | grep -q 'changed=1.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+        run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=1.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
       - name: Output result of config file (only non commented lines)
         run: sed '/ *#/d; /^ *$/d' /etc/telegraf/telegraf.conf
